"""HF data loading and split-building logic for training.

Single source of truth: every run sets ``SPLIT_MANIFEST_DIR=splits/<name>/`` —
``build_mixed_train_val_splits()`` materialises that manifest into the
(merged_hf, train, val, named_val_splits, composition) 5-tuple consumed by
``multihead/train.py`` and ``multihead/finetune.py``.

The legacy ``TRAIN_VAL_MANIFEST`` (1008-batch01 holdout, generated by the
old ``eval/validate.py``) and the no-manifest HF-split fallback have been
removed — neither could guarantee speaker-disjoint splits.
"""

from __future__ import annotations

import os
from pathlib import Path

from datasets import DatasetDict
from dotenv import load_dotenv
from huggingface_hub import login as hf_login

from utils.data import _count_label_presence
from utils.misc import _ALL_TASKS, _KAZEMO_TASKS, REPO_ROOT

SPLIT_MANIFEST_DIR = os.environ.get("SPLIT_MANIFEST_DIR", "").strip()


def _hf_login() -> None:
    load_dotenv(REPO_ROOT / ".env")
    tok = os.environ.get("HF_TOKEN")
    if tok:
        try:
            hf_login(token=tok)
        except Exception:
            pass


def _resolve_split_manifest_dir(raw: str) -> Path:
    p = Path(raw)
    if not p.is_absolute():
        p = REPO_ROOT / p
    p = p.resolve()
    if not p.exists() or not p.is_dir():
        raise FileNotFoundError(f"SPLIT_MANIFEST_DIR not found: {p}")
    if not (p / "config.yaml").exists():
        raise FileNotFoundError(f"SPLIT_MANIFEST_DIR {p} missing config.yaml")
    parquets = [f for f in ("train.parquet", "val.parquet", "test.parquet") if (p / f).exists()]
    if not parquets:
        raise FileNotFoundError(f"SPLIT_MANIFEST_DIR {p} has no train/val/test parquet files")
    return p


def build_splits_from_manifest_dir(split_dir: Path):
    """Load a splits/<name>/ directory and return the legacy training 5-tuple."""
    from splits.materialize import materialize_named_val, materialize_split

    _hf_login()
    split_dir = Path(split_dir)
    print(f"[data] SPLIT_MANIFEST_DIR: {split_dir}")

    splits_map = materialize_split(split_dir)
    named_val_splits = materialize_named_val(split_dir)

    train_split = splits_map.get("train")
    val_split = splits_map.get("val")
    test_split = splits_map.get("test")
    if train_split is None or val_split is None:
        raise RuntimeError(f"SPLIT_MANIFEST_DIR {split_dir} missing train/val after materialize")

    named_val_tasks = {name: set(_ALL_TASKS) for name in named_val_splits}
    if "kazemo" in named_val_tasks:
        named_val_tasks["kazemo"] = set(_KAZEMO_TASKS)

    merged_hf = DatasetDict({"train": train_split, "val": val_split})
    if test_split is not None and len(test_split) > 0:
        merged_hf["test"] = test_split

    composition = {
        "mode": "split_manifest",
        "manifest_dir": str(split_dir),
        "train_total": len(train_split),
        "val_total": len(val_split),
        "test_total": len(test_split) if test_split is not None else 0,
        "train_label_counts": _count_label_presence(train_split),
        "val_label_counts": _count_label_presence(val_split),
        "test_label_counts": _count_label_presence(test_split) if test_split is not None else {},
        "named_val_tasks": named_val_tasks,
    }
    for name, split in named_val_splits.items():
        composition[f"named_val_{name}_size"] = len(split)

    return merged_hf, train_split, val_split, named_val_splits, composition


def build_mixed_train_val_splits():
    """Main entry point for training: returns (merged_hf, train, val, named_val, composition)."""
    if not SPLIT_MANIFEST_DIR:
        raise RuntimeError(
            "SPLIT_MANIFEST_DIR is not set. Every training run must point to a "
            "splits/<name>/ directory built by scripts/build_splits.py."
        )
    return build_splits_from_manifest_dir(_resolve_split_manifest_dir(SPLIT_MANIFEST_DIR))
